[workspace]
members = ["cli", "lib", "viz", "gui", "web"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["knkski"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/knkski/braken"
homepage = "https://knkski.github.io/braken/"
publish = false
