// Generated by cargo run -p braken-gui --example generate_preset_previews.
// Do not edit by hand.

use braken_viz::targets::Palette;

#[cfg(test)]
pub const PRESET_PREVIEW_NAMES: &[&str] = &[
    "3D Hilbert Curve",
    "Anklets of Krishna",
    "Anti-Square Koch Curve",
    "Braken",
    "Branched Snowflake",
    "Circular Tile",
    "Citric Circles",
    "Colored Triangle Gasket",
    "Cordate Leaf",
    "Cross Dragon Curve",
    "FASS Curve",
    "Fiveflake",
    "Forked Bush",
    "Fractal Carpet",
    "Fractal Rhombus Tile",
    "Gosper Curve",
    "Gothic Starwork",
    "Heighway Dragon",
    "Hexagonal Honeycomb",
    "Hilbert Curve",
    "Islands and Lakes",
    "Koch Anti-Snowflake",
    "Koch Crystal",
    "Koch Snowflake",
    "Lanceolate Leaf",
    "Lily-of-the-Valley Flower",
    "Lévy C Curve",
    "Organic Tapered Tree",
    "Orthogonal Virus",
    "Penrose Tiling",
    "Pentaflake",
    "Pentaplex Curve",
    "Pythagorean Tree",
    "Quad Koch Curve",
    "Quadratic Gosper Curve",
    "Quadratic Koch Island",
    "Quadratic Koch Snowflake",
    "Recursive Pentagram",
    "Rhombus Tile",
    "Rose Leaflet",
    "Scaled Fractal Pentagram",
    "Scalloped Hexagon",
    "Sierpiński Arrowhead",
    "Sierpiński Median Curve",
    "Sierpiński Square Curve",
    "Sierpiński Triangle",
    "Spatial Fern",
    "Spatial Four-Way Tree",
    "Spatial Tiered Tree",
    "Sphinx Rep-Tile",
    "Spiral Tiling",
    "Stochastic Plant",
    "Stochastic Sixfold Snowflake",
    "Tapered Binary Tree",
    "Terdragon Boundary",
    "Terdragon Curve",
    "Tiered Fractal Tree",
    "Trapezoid Tile",
    "Triangular Knotwork",
    "Vertigo Spiral",
];

#[rustfmt::skip]
pub fn preset_preview_svg(name: &str, palette: Palette) -> Option<&'static [u8]> {
    match name {
        "3D Hilbert Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/3d-hilbert-curve--effb851c6df36953-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/3d-hilbert-curve--effb851c6df36953-dark.svg").as_slice(),
        }),
        "Anklets of Krishna" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/anklets-of-krishna--5ee126467cc9eea0-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/anklets-of-krishna--5ee126467cc9eea0-dark.svg").as_slice(),
        }),
        "Anti-Square Koch Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/anti-square-koch-curve--be1f9ae411ad30af-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/anti-square-koch-curve--be1f9ae411ad30af-dark.svg").as_slice(),
        }),
        "Braken" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/braken--a549790a43df839a-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/braken--a549790a43df839a-dark.svg").as_slice(),
        }),
        "Branched Snowflake" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/branched-snowflake--adc93a71bed74ba8-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/branched-snowflake--adc93a71bed74ba8-dark.svg").as_slice(),
        }),
        "Circular Tile" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/circular-tile--5ac3300cc033cdb4-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/circular-tile--5ac3300cc033cdb4-dark.svg").as_slice(),
        }),
        "Citric Circles" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/citric-circles--48b7dab786a84c32-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/citric-circles--48b7dab786a84c32-dark.svg").as_slice(),
        }),
        "Colored Triangle Gasket" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/colored-triangle-gasket--2a7a3992a737421a-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/colored-triangle-gasket--2a7a3992a737421a-dark.svg").as_slice(),
        }),
        "Cordate Leaf" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/cordate-leaf--48e9dc3941ce9699-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/cordate-leaf--48e9dc3941ce9699-dark.svg").as_slice(),
        }),
        "Cross Dragon Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/cross-dragon-curve--15f1581b77ff39c1-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/cross-dragon-curve--15f1581b77ff39c1-dark.svg").as_slice(),
        }),
        "FASS Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/fass-curve--5cda9de1b39fc905-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/fass-curve--5cda9de1b39fc905-dark.svg").as_slice(),
        }),
        "Fiveflake" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/fiveflake--6ce73c100182bc72-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/fiveflake--6ce73c100182bc72-dark.svg").as_slice(),
        }),
        "Forked Bush" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/forked-bush--f7c02e979cce39ca-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/forked-bush--f7c02e979cce39ca-dark.svg").as_slice(),
        }),
        "Fractal Carpet" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/fractal-carpet--81ec967fe0e67451-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/fractal-carpet--81ec967fe0e67451-dark.svg").as_slice(),
        }),
        "Fractal Rhombus Tile" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/fractal-rhombus-tile--6fe2aba02c593182-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/fractal-rhombus-tile--6fe2aba02c593182-dark.svg").as_slice(),
        }),
        "Gosper Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/gosper-curve--c85b41e1b29136ac-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/gosper-curve--c85b41e1b29136ac-dark.svg").as_slice(),
        }),
        "Gothic Starwork" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/gothic-starwork--2a20903ce64cc858-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/gothic-starwork--2a20903ce64cc858-dark.svg").as_slice(),
        }),
        "Heighway Dragon" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/heighway-dragon--8e6427924e543ff4-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/heighway-dragon--8e6427924e543ff4-dark.svg").as_slice(),
        }),
        "Hexagonal Honeycomb" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/hexagonal-honeycomb--8f0b2c428889d69c-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/hexagonal-honeycomb--8f0b2c428889d69c-dark.svg").as_slice(),
        }),
        "Hilbert Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/hilbert-curve--79607893f5f850fa-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/hilbert-curve--79607893f5f850fa-dark.svg").as_slice(),
        }),
        "Islands and Lakes" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/islands-and-lakes--c9b9efd1d4a221d8-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/islands-and-lakes--c9b9efd1d4a221d8-dark.svg").as_slice(),
        }),
        "Koch Anti-Snowflake" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/koch-anti-snowflake--d49aae5e76e254c9-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/koch-anti-snowflake--d49aae5e76e254c9-dark.svg").as_slice(),
        }),
        "Koch Crystal" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/koch-crystal--9fabcf5038775956-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/koch-crystal--9fabcf5038775956-dark.svg").as_slice(),
        }),
        "Koch Snowflake" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/koch-snowflake--b9576d603eb93370-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/koch-snowflake--b9576d603eb93370-dark.svg").as_slice(),
        }),
        "Lanceolate Leaf" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/lanceolate-leaf--64a4fb852153c14b-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/lanceolate-leaf--64a4fb852153c14b-dark.svg").as_slice(),
        }),
        "Lily-of-the-Valley Flower" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/lily-of-the-valley-flower--26e6f88479effe04-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/lily-of-the-valley-flower--26e6f88479effe04-dark.svg").as_slice(),
        }),
        "Lévy C Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/l-vy-c-curve--cb6e289b4d6cf96c-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/l-vy-c-curve--cb6e289b4d6cf96c-dark.svg").as_slice(),
        }),
        "Organic Tapered Tree" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/organic-tapered-tree--76af0a6861e9b957-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/organic-tapered-tree--76af0a6861e9b957-dark.svg").as_slice(),
        }),
        "Orthogonal Virus" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/orthogonal-virus--16666a591ce9cbeb-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/orthogonal-virus--16666a591ce9cbeb-dark.svg").as_slice(),
        }),
        "Penrose Tiling" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/penrose-tiling--a6f2e5c924905faa-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/penrose-tiling--a6f2e5c924905faa-dark.svg").as_slice(),
        }),
        "Pentaflake" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/pentaflake--4bf36bb1848f5618-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/pentaflake--4bf36bb1848f5618-dark.svg").as_slice(),
        }),
        "Pentaplex Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/pentaplex-curve--b2becd90fee7cc25-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/pentaplex-curve--b2becd90fee7cc25-dark.svg").as_slice(),
        }),
        "Pythagorean Tree" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/pythagorean-tree--4fd8e15faaf41dc3-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/pythagorean-tree--4fd8e15faaf41dc3-dark.svg").as_slice(),
        }),
        "Quad Koch Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/quad-koch-curve--2c94a5701de4a1d4-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/quad-koch-curve--2c94a5701de4a1d4-dark.svg").as_slice(),
        }),
        "Quadratic Gosper Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/quadratic-gosper-curve--fc41754829bd9956-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/quadratic-gosper-curve--fc41754829bd9956-dark.svg").as_slice(),
        }),
        "Quadratic Koch Island" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/quadratic-koch-island--ce77f715b3a2209f-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/quadratic-koch-island--ce77f715b3a2209f-dark.svg").as_slice(),
        }),
        "Quadratic Koch Snowflake" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/quadratic-koch-snowflake--8c1f8b52096ae5d2-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/quadratic-koch-snowflake--8c1f8b52096ae5d2-dark.svg").as_slice(),
        }),
        "Recursive Pentagram" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/recursive-pentagram--7a7ff748b6d1ed28-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/recursive-pentagram--7a7ff748b6d1ed28-dark.svg").as_slice(),
        }),
        "Rhombus Tile" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/rhombus-tile--2adac1d0150fb081-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/rhombus-tile--2adac1d0150fb081-dark.svg").as_slice(),
        }),
        "Rose Leaflet" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/rose-leaflet--b61d1e7f1948876f-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/rose-leaflet--b61d1e7f1948876f-dark.svg").as_slice(),
        }),
        "Scaled Fractal Pentagram" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/scaled-fractal-pentagram--6f47bb129ee51af5-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/scaled-fractal-pentagram--6f47bb129ee51af5-dark.svg").as_slice(),
        }),
        "Scalloped Hexagon" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/scalloped-hexagon--9e23b042c7a5295c-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/scalloped-hexagon--9e23b042c7a5295c-dark.svg").as_slice(),
        }),
        "Sierpiński Arrowhead" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/sierpi-ski-arrowhead--7bc56727af42881a-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/sierpi-ski-arrowhead--7bc56727af42881a-dark.svg").as_slice(),
        }),
        "Sierpiński Median Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/sierpi-ski-median-curve--20e5fc74b0e98752-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/sierpi-ski-median-curve--20e5fc74b0e98752-dark.svg").as_slice(),
        }),
        "Sierpiński Square Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/sierpi-ski-square-curve--e72bee945e66181f-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/sierpi-ski-square-curve--e72bee945e66181f-dark.svg").as_slice(),
        }),
        "Sierpiński Triangle" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/sierpi-ski-triangle--d61d0af0dda0270f-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/sierpi-ski-triangle--d61d0af0dda0270f-dark.svg").as_slice(),
        }),
        "Spatial Fern" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/spatial-fern--36116a50369298b0-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/spatial-fern--36116a50369298b0-dark.svg").as_slice(),
        }),
        "Spatial Four-Way Tree" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/spatial-four-way-tree--9ebe7adf237f5aa1-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/spatial-four-way-tree--9ebe7adf237f5aa1-dark.svg").as_slice(),
        }),
        "Spatial Tiered Tree" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/spatial-tiered-tree--5c6b6000ee47a30c-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/spatial-tiered-tree--5c6b6000ee47a30c-dark.svg").as_slice(),
        }),
        "Sphinx Rep-Tile" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/sphinx-rep-tile--692784e1626a54c3-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/sphinx-rep-tile--692784e1626a54c3-dark.svg").as_slice(),
        }),
        "Spiral Tiling" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/spiral-tiling--42820bf069c8216f-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/spiral-tiling--42820bf069c8216f-dark.svg").as_slice(),
        }),
        "Stochastic Plant" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/stochastic-plant--87517210c25cad65-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/stochastic-plant--87517210c25cad65-dark.svg").as_slice(),
        }),
        "Stochastic Sixfold Snowflake" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/stochastic-sixfold-snowflake--365d7748a73602b7-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/stochastic-sixfold-snowflake--365d7748a73602b7-dark.svg").as_slice(),
        }),
        "Tapered Binary Tree" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/tapered-binary-tree--7159f34f70f5116f-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/tapered-binary-tree--7159f34f70f5116f-dark.svg").as_slice(),
        }),
        "Terdragon Boundary" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/terdragon-boundary--fd6ad518483a6fc3-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/terdragon-boundary--fd6ad518483a6fc3-dark.svg").as_slice(),
        }),
        "Terdragon Curve" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/terdragon-curve--051493b77aa02680-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/terdragon-curve--051493b77aa02680-dark.svg").as_slice(),
        }),
        "Tiered Fractal Tree" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/tiered-fractal-tree--10d21adb2037a82f-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/tiered-fractal-tree--10d21adb2037a82f-dark.svg").as_slice(),
        }),
        "Trapezoid Tile" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/trapezoid-tile--b7d64e10437d4bed-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/trapezoid-tile--b7d64e10437d4bed-dark.svg").as_slice(),
        }),
        "Triangular Knotwork" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/triangular-knotwork--f7c3a70714b626a7-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/triangular-knotwork--f7c3a70714b626a7-dark.svg").as_slice(),
        }),
        "Vertigo Spiral" => Some(match palette {
            Palette::Light => include_bytes!("../assets/preset-previews/vertigo-spiral--388306610f53eac8-light.svg").as_slice(),
            Palette::Dark => include_bytes!("../assets/preset-previews/vertigo-spiral--388306610f53eac8-dark.svg").as_slice(),
        }),
        _ => None,
    }
}
